name: restaurant_management
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Network
  dio: ^3.0.10
  pretty_dio_logger: ^1.1.1
  retrofit: ^1.3.4+1

  # STATE MANAGEMENT
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  provider: ^6.0.0


  # TOOLS
  intl: ^0.17.0
  flutter_svg: ^0.19.3
  json_annotation: ^3.1.1
  pedantic: ^1.9.2
  build_runner: ^1.11.1
  shared_preferences: ^2.0.7
  nb_utils: ^4.4.7
  fluttertoast: ^8.0.8
  empty_widget: ^0.0.5
  equatable: ^2.0.3
  flutter_native_splash: ^0.3.2

  #UI
  cupertino_icons: ^1.0.2
  pull_to_refresh: ^1.6.4
  google_fonts: ^1.1.2

  #DI
  get_it: ^5.0.0


  flutter_localizations:
    sdk: flutter
  shimmer: ^2.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test: ^1.0.2+3
  mocktail: ^0.1.4
  bloc_test: ^8.0.0
  json_serializable: ^3.5.0
  retrofit_generator: ^1.4.1+3



# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf


flutter_gen:
  integrations:
    flutter_svg: true
flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen.png